"""empty message

Revision ID: f325165eddf8
Revises: 9c5b29ed0302
Create Date: 2023-10-30 09:59:33.656418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f325165eddf8'
down_revision = '9c5b29ed0302'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
