version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.d/default.conf
    depends_on:
      - postmeeting-api
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postmeeting-api:
    image: sehyunsix/postmeeting:0.1.1
    env_file:
      - ./.env
    container_name: postmeeting-api
    ports:
      - '8000:8000'
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  mongo:

