version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    #외부와 소통하는 경우에는 ports로 포트 설정.
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - postmeeting-api
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postmeeting-api:
    image: sehyunsix/postmeeting:0.1.1
    env_file:
      - ./.env
    container_name: postmeeting-api
    ports:
      - '8000:8000'
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  mongo:
  nginx:

